baseURL = 'https://initial-homer-white.netlify.app'
languageCode = 'en-us'
title = "Mike's Hobbies"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'

[markup.goldmark.renderer]
  unsafe = true


MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"



[pagination]
  disableAliases = false
  pagerSize = 6
  path = 'page'


googleAnalytics = ""
enableRobotsTXT = true
enableEmoji = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/golfcart-image.jpg"
  site_logo = ""
  headdescription = "Maintaining and selling golf carts in Versailles, Kentucky.  golf carts, Versailles Kentucky, buggy, gas cart, electric cart."
  #facebook = "https://www.facebook.com/mikeshobbies1/"
  #instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = ""
  recent_posts_number = 3
  cover_dimming_class = "bg-black-50"
  site_header_text_background_color = "rgba(255, 255, 255, 1);"
  page_header_text_background_color = "rgba(255, 255, 255, 1)"
  custom_css = ["css/custom.css"]

[params.ananke.social.follow]
  new_window_icon = false
  networks = [
    "facebook",
  ]

[params.ananke.social.facebook]
profilelink = "https://www.facebook.com/mikeshobbies1/"

[params.ananke.social.email]
profilelink = ""


[[menu.main]]
  identifier = "home"
  name = "Welcome"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "articles"
  name = "Listings"
  url = "/articles/"
  weight = 2 

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 3


